name: Basic-Dispatch-Choice

on:
  workflow_dispatch:
    inputs:
      TEST_PROFILE:
        description: 'Profile to run'
        required: false
        default: ''
        type: choice
        options:
          - MCGWS
          - MCSOS
          - ALL

jobs:
  mcgws:
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.TEST_PROFILE == 'MCGWS' || 
      github.event.inputs.TEST_PROFILE == 'ALL'
    steps:
      - run: echo "Running input ${{ github.event.inputs.TEST_PROFILE }}"
  mcsos:
    runs-on: ubuntu-latest
    needs: mcgws
    if: |
      !cancelled() &&
      (github.event.inputs.TEST_PROFILE == 'MCSOS' || 
      github.event.inputs.TEST_PROFILE == 'ALL')
    steps:
      - run: echo "Running input ${{ github.event.inputs.TEST_PROFILE }}"
